language: php
sudo: false
php:
  - 5.6
  - 7.0
  - hhvm
install: composer install
script: ./vendor/bin/phpunit --coverage-clover clover.xml --testsuite 'Unit Tests'
after_success: sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then ./vendor/bin/coveralls -v; fi'
